import type { Metadata } from "next";
import { Merriweather } from "next/font/google";

import "./globals.css";

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});

export const metadata: Metadata = {
  title: "UNDER SOCIAL AND POLITICS - Menentang Seluruh Keniscayaan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.boxicons.com/fonts/basic/boxicons.min.css" rel="stylesheet"></link>

        <link href="https://cdn.boxicons.com/fonts/brands/boxicons-brands.min.css" rel="stylesheet"></link>
      </head>

      <body className={`bg-app-background-color ${merriweather.className} antialiased`}>{children}</body>
    </html>
  );
}
